define(function(require, exports) {
var errorCode = {
    en: {
        "1" : "Your login status times out. Please re-log in with your Qcloud account first and try again.",
        "4" : "You are not authorized to perform this operation.",
        "1001" : "Under qualification review",
        "1002" : "Failed to pass qualification review",
        "1003" : "You have not set an initial password for your cloud service account. Complete the settings in the management center first and conduct FTP access.",
        "1004" : "You have passed qualification review and LDAP account review. You can enable CDN.",
        "9003" : "The content you entered is incorrect. Please check it and try again.",
        "9089" : "Each account can be accessed to a maximum of 100 CDN domain names. Please pay attention to the number of accessed domain names.",
        "9092" : "Your domain name has been accelerated by CDN. Please confirm whether the domain name has already used CDN.",
        "9093" : "CDN acceleration has been set for the domain name you entered. Contact customer service personnel if you have any questions.",
        "9094" : "The number of URLs cannot exceed 1000.",
        "9103" : "Your domain name cannot be deleted. Only domain names to be authenticated, under review, or disabled can be deleted.",
        "9105" : "Your login status times out. Please re-log in with your Qcloud account first and try again.",
        "9107" : "The domain name you entered is invalid. Please check it and submit again.",
        "9108" : "The source list you entered is invalid. Please check it and submit again.",
        "9109" : "Your cache content is in the incorrect format. Please check it and submit again.",
        "9110" : "The domain name does not exist. Please check it and try again.",
        "9111" : "You have not enabled the CDN service.",
        "9112" : "The refreshed URLs you submitted contain domain names that are not in the \"enabled\" state. Please confirm that the domain names are enabled and try again.",
        "9115" : "The IP you added cannot be a private IP. Please change it and try again.",
        "9116" : "The IPs you submitted exceed the quantity limit. Please enter again. Contact customer service personnel if required.",
        "9120" : "The traffic package has expired. Please refresh the page and try again.",
        "9121" : "The traffic package has been used. Please refresh the page and try again.",
        "9122" : "The effective date you selected is incorrect. Please refresh the page and try again.",
        "9123" : "The user has enabled the CDN. Please refresh the page and try again.",
        "9124" : "This preferential traffic package activity has not started.",
        "9125" : "This preferential traffic package activity has ended.",
        "9126" : "The time value is incorrect.",
        "9127" : "The type value is incorrect.",
        "9128" : "The file suffix is incorrect.",
        "9129" : "The directory is incorrect.",
        "9130" : "Anti-leeching error.",
        "9131" : "The anti-leeching type is incorrect.",
        "9132" : "The anti-leeching list is incorrect.",
        "9133" : "The anti-leeching content is incorrect.",
        "9135" : "Your application for adding a domain name has been submitted. Please wait.",
        "9140" : "Failed in domain name ownership authentication. Please ensure that your authentication steps are correct.",
        "9141" : "Sorry. The domain name has been accessed to the CDN system.",
        "9142" : "Sorry. The domain name has been accessed to Dayu Distributed Defense system.",
        "9149" : "The month in the monthly operation report is invalid.",
        "9150" : "The statistical analysis date is invalid.",
        "9152" : "The query format of CDN monitoring data is incorrect.",
        "9159" : "Consumption has taken place in your current charging cycle. The changed charging mode cannot take effect immediately.",
        "9161" : "Protection has been manually set for this domain name on the server. If you need to modify the domain name, contact customer service personnel or key account manager for manual handling.",
        "9162" : "Your referer contains more than 200 pieces. Please enter the referer according to specifications.",
        "9163" : "Frequent configuration will prolong the time for the configuration to take effect. Please try again later.",
        "9165" : "You have not logged into WeChat.",
        "9166" : "The added domain name list is blank.",
        "9167" : "The bound QQ account is inconsistent with the login QQ account.",
        "9168" : "The WeChat number has been bound.",
        "9169" : "Disabled account. The operations are limited.",
        "9170" : "Account in trial mode. The operations are limited.",
        "9171" : "Interface parameter input error. Please try again later.",
        "9172" : "Excessive domain names are added in batches.",
        "9173" : "An error occurs on the traffic package configuration.",
        "9174" : "An error occurs in the batch addition of domain names.",
        "9175" : "Under deployment",
        "9176" : "The domain name has been offline.",
        "9177" : "The domain name has been online.",
        "9178" : "The sub-account already exists.",
        "9179" : "The sub-account does not exist.",
        "9180" : "The sub-account type is invalid.",
        "9181" : "Failed to create the SVN subdirectory.",
        "9182" : "An error occurs in the calling of the FTP API.",
        "9184" : "Password error.",
        "9185" : "Failed to roll back the sub-account.",
        "9186" : "Failed to add the sub-account.",
        "9187" : "Failed to delete the sub-account.",
        "9188" : "Failed to reset the sub-account password.",
        "9189" : "Failed to bind the FTP sub-account.",
        "9190" : "Failed to unbind the FTP sub-account.",
        "9191" : "A sub-account already exists under the project.",
        "9192" : "The cache time unit is incorrect.",
        "9193" : "Invalid port of the source site.",
        "9194" : "The cache parameters are set incorrectly.",
        "9195" : "Failed to bind the project. Check whether the project has already used the FTP hosting source.",
        "9197" : "You are not authorized to perform operations on the cooperated domain name.",
        "9198" : "The source site of the cooperated domain name is invalid.",
        "9199" : "The source site of the cooperated domain name is not contained in your CVM list.",
        "9302" : "Your domain name has been accelerated by CDN. Please confirm whether the domain name has already used CDN.",
        "9303" : "The domain name you entered is invalid. Please check it and submit again.",
        "9305" : "The source list you entered is invalid. Please check it and submit again.",
        "9310" : "Your operations are very frequent. Please take a rest and try again later.",
        "9311" : "The refreshed URLs you submitted contain URLs in the incorrect format. Please check it and try again.",
        "9312" : "Domain name configuration is under deployment. Please wait for a moment and try again after the configuration takes effect.",
        "9320" : "Your cache content is in the incorrect format. Please check it and submit again.",
        "9393" : "The domain name you entered has been accessed in the COS system. Delete it from the COS system first and add it again.",
        "9394" : "The domain name you entered has been accessed in the Cloud Image system. Delete it from the Cloud Image system first and add it again.",
        "9395" : "The domain name you entered has been accessed in Dayu Distributed Defense system. Delete it from Dayu Distributed Defense system first and add it again.",
        "9400" : "Reading data failed. Please try again later.",
        "20004" : "The current domain name is not filed with the Ministry and Information Technology of the People's Republic of China.",
        "20005" : "The current domain name cannot use CDN on the Qcloud.",
        "20006" : "It is detected that the current domain name contains invalid information. Please complete website appeal successfully on Tencent PC Manager first and submit for review.",
        "20007" : "The entered source site does not conform to rules.",
        "20008" : "An exception occurs on the access to Port 80 of the source site.",
        "22035" : "SSL type error.",
        "22043" : "Excessive URLs are refreshed at a time.",
        "22044" : "The number of refreshed URL entries exceeds the limit of a single day.",
        "22045" : "Excessive directories are refreshed at a time.",
        "22046" : "The number of refreshed directory entries exceeds the limit of a single day.",
        "22047" : "The whitelist data already exists.",
        "22048" : "Failed to add data.",
        "22049" : "The whitelist data does not exist.",
        "22050" : "The whitelist data already exists.",
        "22051" : "Failed to add data.",
        "22052" : "Failed to modify data.",
        "22053" : "There is dirty data in the whitelist.",
        "22055" : "Please publish files to the CDN node on the \"Upload via SVN\" page.",
        "22057" : "FTP synchronization failed.",
        "22058" : "Not in the whitelist.",
        "22059" : "ftp sync is called too frequently.",
        "22060" : "The ftp sync calling count exceeds the limit.",
        "22061" : "Monthly settlement data error.",
        "22062" : "Directory-based refresh does not support file paths with upper-case English letters. Please try again.",
        "22063" : "Too frequent operation. Please try again later.",
        "22400" : "An exception occurs in the calling of the COS API.",
        "22401" : "Invalid bucket.",
        "22402" : "Binding the bucket failed.",
        "22403" : "It is forbidden to modify the bucket.",
        "22701" : "Invalid domain name.",
        "22702" : "The domain name is not resolved to the CDN.",
        "22704" : "The intermediate source and HTTPS retrieval cannot be used at the same time.",
        "22706" : "Invalid email format.",
        "22708" : "Failed to get license information.",
        "22709" : "The license does not match the domain name.",
        "22710" : "The license does not match the private key.",
        "22711" : "The license has expired.",
        "22800" : "System error. Please try again later.",
        "22801" : "This voucher activity does not exist.",
        "22802" : "This voucher activity has not started.",
        "22803" : "This voucher activity has ended.",
        "22804" : "All vouchers have been claimed. Thank you for your participation.",
        "22805" : "Vouchers of today have been claimed.",
        "22806" : "You have already claimed a voucher. Each user is allowed to claim only once.",
        "22807" : "This voucher activity has ended.",
        "23000" : "The authorized folder of the FTP sub-account does not exist.",
        "9340" : "HTTPS retrieval does not support domain names.",
        "9183" : "Failed to bind the SVN sub-account to the default item.",
        "9196" : "Failed to get the CVM list.",
        "22056" : "The number of cooperated domain names exceeds the limit.",
        "22036" : "SSL domain name error."
    }
}

var map = {
};
map.errorCode = errorCode;

return map;
});/*  |xGv00|dbbe3a5d43b25a6c5ff686975f4a6abd */